### PR TITLE
Dinger1986 add confirm and info for enable sync

### PR DESCRIPTION
**Pull request by dinger1986**
Reworded from Sync MeshCentral Users/Permissions with TRMM: to Control Mesh Permissions from TRMM:, added info button (which probably needs reworded) and a confirmation yes/no for enabling and disabling the sync

### CODE REVIEW

**Comment by wh1te909** [comment]
thx, fixed wording

**Comment by dinger1986** [comment]
Wording is better, I did change to Mesh after noticing that all the other settings refer to it as Mesh not MeshCentral

**Comment by wh1te909** [comment]
Ah I didn't even notice, I actually shortened it cuz the little info icon kept moving under the text, I wanted it to the right. Too lazy to figure out the CSS for that so I just shorted the words so it fits xD. I'll change it to Mesh, that will help even more.

**Comment by dinger1986** [comment]
Perfect. Otherwise wording is better than mine. I more wrote something so something was there 🤷‍♂️

**Pull request merged**
